# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
[
  {
    goPackagePath = "github.com/BurntSushi/toml";
    fetch = {
      type = "git";
      url = "https://github.com/BurntSushi/toml";
      rev = "7801cfbfa61253e560e81ab68cb628f6b9ecd762";
      sha256 = "0hgh70qlm6qhxmhn7cfxs4zl8rq0q5iwqx8g9ydcn0l9fh9hfs57";
    };
  }
  {
    goPackagePath = "github.com/akiyosi/goqtframelesswindow";
    fetch = {
      type = "git";
      url = "https://github.com/akiyosi/goqtframelesswindow";
      rev = "7626a8ddb7a9146bf869c8ac3ab08adf3fe046a4";
      sha256 = "1v1j1nl72nn6481733bsf32n6d4k00xa9rwwhlirrwfczgfn22c2";
    };
  }
  {
    goPackagePath = "github.com/akiyosi/short_path";
    fetch = {
      type = "git";
      url = "https://github.com/akiyosi/short_path";
      rev = "68a4d8ef8723f4a1a2d84da926c848a036ceebfa";
      sha256 = "0j1d4qz1gdpmvmarb7qj8ikfx6wpiihax0w67wxv1qqd104vcqpi";
    };
  }
  {
    goPackagePath = "github.com/atotto/clipboard";
    fetch = {
      type = "git";
      url = "https://github.com/atotto/clipboard";
      rev = "1438b322bde482cc6decd8bc53dbe2eece57668b";
      sha256 = "1m2mv37g2w929hfmf8wra1mz71xzj4lb8lir8ahdyvp67542v8xl";
    };
  }
  {
    goPackagePath = "github.com/bluele/gcache";
    fetch = {
      type = "git";
      url = "https://github.com/bluele/gcache";
      rev = "d8b7e051c564c174fea6ef60d180abf601099015";
      sha256 = "18ajg5gyrwaimi7b7q16mils6wn1n2p7bm31h0ppm4sj8gy5zsxd";
    };
  }
  {
    goPackagePath = "github.com/jessevdk/go-flags";
    fetch = {
      type = "git";
      url = "https://github.com/jessevdk/go-flags";
      rev = "3927b71304df5ef738c74bfe7a3216d218a60779";
      sha256 = "0qgmk9l321dpj965k6aknygy3l3vx0fi8mx73pgc5gs8nzmlxqic";
    };
  }
  {
    goPackagePath = "github.com/mattn/go-isatty";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-isatty";
      rev = "ed75e619dc0f0489fd4062163a7d061eaa249b9c";
      sha256 = "1dnkvnnrdrg3xlzbs3cw29fwqsln742hj1iajx32gflfsl2b4fag";
    };
  }
  {
    goPackagePath = "github.com/mitchellh/go-homedir";
    fetch = {
      type = "git";
      url = "https://github.com/mitchellh/go-homedir";
      rev = "af06845cf3004701891bf4fdb884bfe4920b3727";
      sha256 = "0ydzkipf28hwj2bfxqmwlww47khyk6d152xax4bnyh60f4lq3nx1";
    };
  }
  {
    goPackagePath = "github.com/neovim/go-client";
    fetch = {
      type = "git";
      url = "https://github.com/neovim/go-client";
      rev = "8a0d4706f1fa4f685b43b9a577e4333e133d7521";
      sha256 = "0x72zbz4z8qd4hdk6znmrwzz34c6k41fqqzan5idb2shk71clsxk";
    };
  }
  {
    goPackagePath = "github.com/therecipe/qt";
    fetch = {
      type = "git";
      url = "https://github.com/therecipe/qt";
      rev = "c0c124a5770d357908f16fa57e0aa0ec6ccd3f91";
      sha256 = "197wdh2v0g5g2dpb1gcd5gp0g4wqzip34cawisvy6z7mygmsc8rd";
    };
  }
  {
    goPackagePath = "golang.org/x/sys";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/sys";
      rev = "b36040661688bbbde06c38ea80af105ebf21415b";
      sha256 = "1b63v4fw9hr1y3yqzscv1an4q10m2qnmkxcp7w7chi2gbfqr7ih4";
    };
  }
]
